DELETE http://localhost:3003/api/blogs/65eeb603b9aec8ca32202009
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFBQSIsImlkIjoiNjVlZWIzNjA2ODBiODNmOTU0OTkzYjJjIiwiaWF0IjoxNzEwMTQ0MzM3LCJleHAiOjE3MTA1MDQzMzd9.4nxHO0ht5EK6C_P6aR3OxjWlRgB0t-ZzYS5ot4wJ6CY