POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFBQSIsImlkIjoiNjVlZWIzNjA2ODBiODNmOTU0OTkzYjJjIiwiaWF0IjoxNzEwMTQyODk5LCJleHAiOjE3MTAxNDY0OTl9.RMQmwYfOzPCwDayly4hKRKGVJzNnTpztIe8NLXVXiYU

{
      "title": "Full Stack Open",
      "author": "Kalle Luukkainen",
      "url": "www.hyo.com",
      "likes" : 200
}