POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlQxMDAwIiwiaWQiOiI2NWVhZWRiYzNmYjk0NzQ3MjI3ODE2ZGEiLCJpYXQiOjE3MDk4OTk3MDYsImV4cCI6MTcwOTkwMzMwNn0.S9IBcrjEGvVRzS0rSSnQCHtiECwgH4LBZMNPdtEBY2Q

{
      "title": "Full Stack Open",
      "author": "Matti Luukkainen",
      "url": "www.hyo.com",
      "likes" : 200
}